### ISSUE TITLE
Careers First Section

### ISSUE THREAD

**Issue by MhamadR** [rozhiar-tech/Happy#28]
## Summary

Create first section of careers page.

### Screenshots
![2023-01-10 15_36_10-Online Therapist – Figma](https://user-images.githubusercontent.com/59586466/211565701-381ca15b-23ea-4438-9a9a-213744daa9da.jpg)

### Constriants / Details

- [ ] Make it responsive
- [ ] Use the button style that we agreed on

**Comment by Zoristar** [comment]
Done
