### ISSUE TITLE
Create Account

### ISSUE THREAD

**Issue by MhamadR** [rozhiar-tech/Happy#31]
## Summary

Implement create account page.

### Screenshots
![2023-01-10 15_45_07-Online Therapist – Figma](https://user-images.githubusercontent.com/59586466/211568339-69757c30-233f-4472-bfd7-9932b8709049.jpg)

### Constriants / Details
- [ ] Make it responsive
- [ ] Style the button the way we agreed on
- [ ] Make it functional, connect it to firebase

**Comment by Zoristar** [comment]
Done
